### ISSUE TITLE
various questions

### ISSUE THREAD

**Issue by bkardell** [dbaron/container-queries-implementability#2]
Just linking this up in a handier way since I see it being shared now and I don't want them to get lost... some of the commits, as you already know, have comments like

https://github.com/dbaron/container-queries-implementability/commit/f839c148fc384d4392566e541e8a986e0b51579e#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by dbaron** [comment]
I'm planning to archive this repository shortly.  If this issue is still relevant, it should be raised [in the CSS Working Group's repository](https://github.com/w3c/csswg-drafts/labels/css-contain-3).
