### ISSUE TITLE
how does this interact with relayout caused by adding or removing scrollbars outside of the container?

### ISSUE THREAD

**Issue by dbaron** [dbaron/container-queries-implementability#3]
In the [face-to-face discussion of this proposal](https://lists.w3.org/Archives/Public/www-style/2020May/0002.html), @frivoal raised the issue of how containment in one dimension (proposed here) interacts with layout changes in one dimension causing a layout change in the other dimension via something *outside* the container.  He raised the example of such layout changes causing adding or removing of scrollbars.

This leads me to two thoughts:

First, I think it may be that adding and removing scrollbars is the only existing mechanism that can cause this problem.  I might be wrong, but I'd be interested in other examples.

Second, the problem of adding and removing scrollbars *already* has to deal with breaking infinite loops in ways that can cause "incorrect" layouts, or more than one possible layout.  For example, there are two possible correct layouts of this (with normal non-overlay scrollbars):
```html
<div style="width: 100px; height: 100px">
  <div style="overflow: auto">
    <div style="width: 100px; height: 100px">
    </div>
  </div>
</div>
```
(with both scrollbars, or without both scrollbars) and the one that is used in existing implementations can be a function of the sequence of dynamic changes that led to this situation.  Or to take another example, there are zero possible technically-correct layouts of this (with normal non-overlay scrollbars):
```html
<div style="width: 99px; height: 100px">
  <div style="overflow: auto; flex: 1">
    <img style="display: block; height: 100%" src="[square image]">
  </div>
</div>
```
yet at least Gecko and Chromium seem to do the same thing.

So I'm thinking that maybe this notion of containment in one dimension doesn't actually create a new problem -- it just makes an existing problem (that we've already solved in implementations but haven't specified) happen in an additional case.

So maybe the underlying thing we need to do here is specify how layout loops caused by addition and removal of scrollbars are broken?  (Yes, it's unpleasant and slower than it should be, and we should avoid it, perhaps using [`scrollbar-gutter`](https://drafts.csswg.org/css-overflow-4/#scrollbar-gutter-property), but maybe it's not something new and fundamental?)

Does this make sense?

**Comment by frivoal** [comment]
First, I think it may be that adding and removing scrollbars is the only existing mechanism that can cause this problem. I might be wrong, but I'd be interested in other examples.

It is the only example I am sure of. I wonder if it might be possible to craft something with the same problem using the [`aspect-ratio`](https://drafts.csswg.org/css-sizing-4/#aspect-ratio) property, as I feel there might be something problematic there, but I am not sure how to cause this problem.

If it is limited to scrollbars, that would be a very good news indeed. There'd still be something to solve, but it would no longer be an open ended problem.

**Comment by dbaron** [comment]
I'm planning to archive this repository shortly.  If this issue is still relevant, it should be raised [in the CSS Working Group's repository](https://github.com/w3c/csswg-drafts/labels/css-contain-3).
